version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5430:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123*
      - POSTGRES_DB=person